# Default values for static-website.
replicaCount: 2

image:
  repository: REGISTRY_PLACEHOLDER/static-website
  tag: VERSION_PLACEHOLDER
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
  hosts:
    - host: static-website.example.com
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: static-website-tls
      hosts:
        - static-website.example.com

resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

# Database configuration
database:
  enabled: true
  type: postgresql
  host: postgresql.database
  port: 5432
  database: staticwebsite
  username: appuser
  existingSecret: db-credentials
  existingSecretKey: password

# Monitoring configuration
monitoring:
  enabled: true
  serviceMonitor:
    enabled: true
    interval: 15s
