apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: helm-charts
  namespace: flux-system
spec:
  interval: 5m
  url: https://charts.example.com  # Replace with your chart repository URL
