{{- if and .Values.monitoring.enabled .Values.monitoring.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "static-website.fullname" . }}
  labels:
    {{- include "static-website.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "static-website.selectorLabels" . | nindent 6 }}
  endpoints:
  - port: http
    interval: {{ .Values.monitoring.serviceMonitor.interval }}
    path: /metrics
{{- end }}
